FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install uv && uv pip install --system --no-cache --index-strategy unsafe-best-match -r requirements.txt

COPY ./app /app/app
COPY ./tests /app/tests
COPY ./datasets /app/datasets
COPY ./data /app/data

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
