from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    query: str = Field(..., description="The user's question or support query", examples=["How do I reset my password?"])
    chat_history: list[dict] = Field(default=[], description="Previous conversation messages for context")
    session_id: str | None = Field(default=None, description="Session ID for conversation continuity")

class SourceCitation(BaseModel):
    source: str = Field(..., description="Source document filename", examples=["faq.md"])
    page: int | None = Field(default=None, description="Page number if applicable")
    chunk_id: str | None = Field(default=None, description="Chunk identifier")
    doc_id: str | None = Field(default=None, description="Document identifier")
    snippet: str = Field(..., description="Relevant text excerpt", examples=["To reset your password, go to Settings > Security."])

class ChatResponse(BaseModel):
    query: str = Field(..., description="The original query")
    answer: str = Field(..., description="Generated answer with citations")
    sources: list[SourceCitation] = Field(default=[], description="Source citations for the answer")
    confidence: float = Field(default=0.0, description="Answer confidence score (0-1)", ge=0, le=1)
    session_id: str = Field(default="default", description="Session identifier")

class IngestionRequest(BaseModel):
    data_dir: str = Field(default="data/docs", description="Directory containing documents to ingest")
    force: bool = Field(default=False, description="Whether to clear existing index before ingestion")

class FeedbackRequest(BaseModel):
    query: str = Field(..., description="The query the user is providing feedback on")
    answer: str = Field(..., description="The answer generated by the system")
    is_positive: bool = Field(default=True, description="Whether the feedback is positive or negative")
    comments: str | None = Field(default=None, description="Optional text feedback from the user")

class InterveneRequest(BaseModel):
    message: str = Field(..., description="The message content to intervene with")
    role: str = Field(default="assistant", description="The role of the message sender")
